### ISSUE TITLE
Obstacle - View: The map no longer wants to show.

### ISSUE THREAD

**Issue by sca075** [sca075/mqtt_vacuum_camera#295]
Reported by: @borgqueenx
Bug found: I cannot get away from images now. The map no longer wants to show. I tried clicking around, see the youtube video.
On first try, a second other image opened. (without being in map view). but now i cant get out.
https://youtu.be/Z-0cEJdjHaQ

_Originally posted by @borgqueenx in https://github.com/sca075/mqtt_vacuum_camera/issues/286#issuecomment-2518072945_

**Comment by sca075** [comment]
@borgqueenx I just posted some changes if all the test will pass I will publish a beta.

**Comment by sca075** [comment]
@borgqueenx I just released 2024.12.1 can you please give it a try and let me know if it works now?

**Comment by richii93** [comment]
I do have the same problem with version 2024.12.1.

**Comment by sca075** [comment]
@richii93 I uploaded as beta as I'm working with @borgqueenx to solve it. Please give a try to the 2024.12.2b0  and if still not work (in discussion #296 more details) please let us know. In any cases yesterday we did identify the root cause (missing scenario in my development tests). I think is a easy fix..

**Comment by richii93** [comment]
I tried version 2024.12.2b0 - but it doesn’t fix it for me.

**Comment by borgqueenx** [comment]
Same, it is not fixed. It wont switch back to camera view when docked.

**Comment by sca075** [comment]
@borgqueenx  and @richii93 
I'm just back from work and I had a look to the code.. I just want to share what we are going to do:
- Before that the camera is going to acquire the data for downloading the image, it will save a backup of the self.Image datas.
- As soon we get the event to switch back to camera_view:
1) check if the vacuum is docked or not (in this case we go to 3)
2) if docked -> send the backup image to the camera output.
3) change the mode.

This is in general what was the idea before I released the b0.. but in the last minute (also because I changed something in my test scenario that allow me to switch from test image to the real vacuum image (and honestly it worked as the V1 is pushing the data constantly to valetudo).. it looks yours X10 / X40 when docked do not send this data from what you reported and then.. the above looks to be the optimal. I will release this night another beta just to let you confirm, only then I close this issue. 

Thanks you,
Sandro

**Comment by richii93** [comment]
Now it also works for my Dreame D10S (with Valetudo) when docked. Thank you.

**Comment by sca075** [comment]
I will add a condition (I forgot it) that checks if the vacuum is in dock in the return to camera_mode. Luckily I didn't release yet the official 12.2 ;)

Thanks again for the input

**Comment by sca075** [comment]
@borgqueenx 
Hope that now with 2024.12.2 all is working as expected, in your case using the 1:1 aspect ratio the obstacle images might fit the same ratio of the images. Unfortunately I didn't found a way to say to the card to remove the zoom (I'm still checking when there is an event I can send to the card for this). 
As I wrote on the RN I would focus now just on the refactoring and make adjustments to the code.. but I will see also if we can get some small icons on the card showing what kind of obstacle the vacuum found ;)
